name: ðŸ§ª Test with coverage ðŸ“Š

on:
  workflow_call:

jobs:
  coverage:
    name: ðŸ§ª Test
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: ðŸ“š Git Checkout
        uses: actions/checkout@v4
      - name: ðŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: âš™ï¸ Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: âš™ï¸ Setup Melos
        uses: bluefireteam/melos-action@v2
      - name: ðŸ“¦ Install Dependencies
        run: |
          flutter pub global activate flutter_gen
          melos get
      - name: ðŸ“¦ Prepare .env
        run: |
          cd shared/config
          cp .env.example .env.dev
          cp .env.example .env
          cp .env.example .env.stg
      - name: ðŸ“¦ Run build_runner
        run: melos build
      - name: ðŸ“¦ Synchronize Dependencies
        run: melos get
      - name: âœ¨ Fix Formatting
        run: melos format
      - name: âœ¨ Check Formatting
        run: melos format-check
      - name: ðŸ•µï¸ Analyze
        run: melos analyze
      - name: ðŸ§ª Run tests with coverage
        run: melos test:with-lcov-coverage
      - name: ðŸ§ªâœ…âŒ Publish test results
        id: compute_test_results
        uses: dorny/test-reporter@v1.6.0
        with:
          name: "ðŸ§ªðŸ“Š Unit tests report"
          path: test_reports/*_test_report.json
          reporter: "flutter-json"
          max-annotations: "50"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ðŸ§ªðŸ“Š Publish coverage report
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: coverage_report/cleaned_combined_lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: "Coverage Report"
      - name: ðŸ¥¤ Extract test coverage percentage
        run: |
          melos run test:generate-html-coverage
          grep -o '.*headerCovTableEntryLo.*' coverage_report/index.html | sed -E  's/.*>(.*) %<.*/\1/' > coverage_percentage.txt
          percentage=$(cat coverage_percentage.txt)
          echo "Coverage percentage: $percentage"
          echo "coverage_percentage=$percentage" >> $GITHUB_ENV
